[package]
name = "thinkos-node"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
colored = "2"
thinkos-cmps = { path = "../runtime/cmps" }

[profile.release]
lto = "thin"
codegen-units = 1
