[package]
name = "thinkos-node"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
anyhow = "1"
thinkos-cmps = { path = "../runtime/cmps" }
