name: CMPS Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cmps-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build & Test CMPS
        run: |
          cd chain/runtime/cmps
          cargo test -- --nocapture
