name: Lint & Smoke (Python)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Print versions
        run: |
          python -V
          pip -V

      - name: Install AIFA deps if present
        if: ${{ hashFiles('aifa/engine/requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r aifa/engine/requirements.txt

      - name: Byte-compile explorer if present
        if: ${{ hashFiles('explorer/cogniscan-lite/app.py') != '' }}
        run: python -m py_compile explorer/cogniscan-lite/app.py
