name: Lint & Smoke (Python)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        py: [ "3.11" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==24.8.0 ruff==0.6.9 fastapi uvicorn

      - name: Lint (black + ruff)
        run: |
          black --check explorer/cogniscan-lite || true
          ruff check explorer/cogniscan-lite || true

      - name: Smoke Test
        run: |
          python -m compileall explorer/cogniscan-lite || true


