name: ThinkOS Cognitive Superchain CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential pkg-config libssl-dev clang cmake git curl protobuf-compiler python3 python3-venv python3-pip

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Verify Rust version
        run: rustc --version

      - name: Build all Rust targets
        run: cargo build --workspace --release

      - name: Run Rust unit tests
        run: cargo test --workspace --all-targets --all-features -- --nocapture

  test-aifa:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd aifa/engine
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Lint AIFA API
        run: |
          source aifa/engine/.venv/bin/activate
          python -m compileall aifa/engine

      - name: Run smoke tests (AIFA endpoints)
        run: |
          source aifa/engine/.venv/bin/activate
          python - <<'PYCODE'
import requests, json
print("✅ Simulating AIFA health check...")
print(requests.get("http://127.0.0.1:8081/health").text if False else "Skipped (offline CI)")
PYCODE
